// dissapearance of Night - Day Button

var indoorScenes = [
    // academic area
    "academic_room_day",
    "academic_room_night",
    "APS_room_day",
    "APS_room_night",
    "conference_room_day",
    "conference_room_night",
    "DSA_center_day",
    "DSA_center_night",
    // lab area,
    "electronics_lab_day",
    "electronics_lab_night",
    "mechatronics_lab_day",
    "mechatronics_lab_night",
    "mechanical_lab_day",
    "mechanical_lab_night",
    "manufacturing_lab_day",
    "manufacturing_lab_night",
    "physics_lab_day",
    "physics_lab_night",
    "vlsi_lab_day",
    "vlsi_lab_night",
    "pandc_lab_day",
    "pandc_lab_night",
    // sac 
    "saaz_day",
    "saaz_night",
    "tt_day",
    "tt_night",
    "badminton_day",
    "badminton_night",
    "gym_day",
    "gym_night",
    "kabaddi_day",
    "kabaddi_night",
    "court_day",
    "court_night",
    // hostel area
    "panini_canteen_day",
    "panini_canteen_night",
    "H3_canteen_day",
    "H3_canteen_night",
    "H3_entry_day",
    "H3_entry_night",
    "H4_canteen_day",
    "H4_canteen_night",
    "H4_entry_day",
    "H4_entry_night",
    "H1_canteen_day",
    "H1_canteen_night",
    "afc_day",
    "afc_night",
    "ers_day",
    "ers_night",
    // "MS_canteen_day",
    // "MS_canteen_night",
    // mess 
    "mess_day",
    "mess_night",
    //cc lab
    "lab1_day",
    "lab1_night",
    "lab2_day",
    "lab2_night",
    "lab3_night",
    "lab3_day",
    "reading_room_day",
    "reading_room_night",
    "library_center_day",
    "library_center_night",
    "library_day",
    "library_night",
    "seminarhall_day",
    "seminarhall_night",
    "tinkering_lab_day",
    "tinkering_lab_night",
    "computer_lab_day",
    "computer_lab_night",
    // LHTC
    "LHTC_102_day",
    "LHTC_102_night",
    "LHTC_104_day",
    "LHTC_104_night",
    "LHTC_cr_day",
    "LHTC_cr_night",
    "LHTC_103_day",
    "LHTC_103_night",
    "LHTC_design1_day",
    "LHTC_design1_night",
    "LHTC_design2_day",
    "LHTC_design2_night",
    "LHTC_design3_night",
    "LHTC_design3_day",
    "racing_day",
    "racing_night",
    "racing2_day",
    "racing2_night",
    // hexagon
    "hexagon_day",
    "hexagon_night",
    "Oat_day",
    "Oat_night",
    "rewa_day",
    "rewa_night",
    "narmada_day",
    "narmada_night"
    
];